const { baseStyles } = require("./src/baseStyles");

module.exports = {
  defaultCss: baseStyles,
  useRtl: true,
  breakpoints: {
    sm: "768px",
    md: "992px",
    lg: "1200px",
  },
  custom: {
    "font-primary": "var(--font-primary)",
    "font-secondary": "var(--font-secondary)",
    "font-tertiary": "var(--font-tertiary)",
    "font-quaternary": "var(--font-quaternary)",
    "color-primary": "var(--color-primary)",
    "color-secondary": "var(--color-secondary)",
    "color-tertiary": "var(--color-tertiary)",
    "color-quaternary": "var(--color-quaternary)",
    "color-dark": "var(--color-dark)",
    "color-gray9": "var(--color-gray9)",
    "color-gray8": "var(--color-gray8)",
    "color-gray7": "var(--color-gray7)",
    "color-gray6": "var(--color-gray6)",
    "color-gray5": "var(--color-gray5)",
    "color-gray4": "var(--color-gray4)",
    "color-gray3": "var(--color-gray3)",
    "color-gray2": "var(--color-gray2)",
    "color-gray1": "var(--color-gray1)",
    "color-light": "var(--color-light)",
    "color-variable-16": "var(--color-variable-16)",
    "color-variable-17": "var(--color-variable-17)",
    "color-variable-18": "var(--color-variable-18)",
    "color-variable-19": "var(--color-variable-19)",
    "color-variable-20": "var(--color-variable-20)",
    "color-variable-21": "var(--color-variable-21)",
    "color-variable-22": "var(--color-variable-22)",
    "color-variable-23": "var(--color-variable-23)",
    "color-variable-24": "var(--color-variable-24)",
    "color-variable-25": "var(--color-variable-25)",
    "font-variable-5": "var(--font-variable-5)",
    "font-variable-6": "var(--font-variable-6)",
    "font-variable-7": "var(--font-variable-7)",
    "font-variable-8": "var(--font-variable-8)",
    "font-variable-9": "var(--font-variable-9)",
    "font-variable-10": "var(--font-variable-10)",
    "font-variable-11": "var(--font-variable-11)",
    "font-variable-12": "var(--font-variable-12)",
    "font-variable-13": "var(--font-variable-13)",
    "font-variable-14": "var(--font-variable-14)",
  },
};
